# Generated by Django 3.2.7 on 2021-09-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='text',
        ),
    ]
